name: images_files_checker
description: A CLI tool that checks each image in the project and report missing files or incorrect image resolution.
repository: https://github.com/talesbarreto/images_files_checker
version: 1.0.3

executables:
  images_files_checker:

environment:
  sdk: '>=2.17.1 <4.0.0'

dependencies:
  args: ^2.4.2
  image: ^4.2.0

dev_dependencies:
  lints: ">=2.0.0 <6.0.0"
  test: ^1.16.0
  mockito: ^5.2.0
