// Mocks generated by Mockito 5.2.0 from annotations
// in images_files_checker/test/domain/checkers/use_cases/register_missing_asset_files_test.dart.
// Do not manually edit this file.

import 'package:images_files_checker/src/domain/assets_entries/models/asset_density.dart'
    as _i3;
import 'package:images_files_checker/src/domain/assets_entries/use_cases/get_expected_densities.dart'
    as _i2;
import 'package:images_files_checker/src/domain/user_options/models/user_options.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [GetExpectedDensities].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExpectedDensities extends _i1.Mock
    implements _i2.GetExpectedDensities {
  @override
  List<_i3.AssetDensity> call(_i4.UserOptions? userOptions) =>
      (super.noSuchMethod(Invocation.method(#call, [userOptions]),
          returnValue: <_i3.AssetDensity>[]) as List<_i3.AssetDensity>);
}
